// src/workers/outreach-worker.js
// ─────────────────────────────────────────────────────────────
// Sends AI-personalized cold email sequences to prospecting leads.
// Each email is generated by Claude Haiku based on lead data.
// Sends via Gmail SMTP (Nodemailer).
// Runs every 30 minutes from index.js.
//
// Required env vars:
//   GMAIL_USER        → dan@novuleads.com
//   GMAIL_APP_PASS    → app password from Google Account settings
//   ANTHROPIC_API_KEY → already set in your Railway env
// ─────────────────────────────────────────────────────────────
'use strict';

require('dotenv').config();

const nodemailer = require('nodemailer');
const Anthropic  = require('@anthropic-ai/sdk');
const supabase   = require('../../config/supabase');

const BATCH_SIZE  = 25;
const DELAYS_DAYS = [3, 4]; // days until next email after each step

// ── Gmail transporter (lazy init) ────────────────────────────
let _transporter = null;

function getTransporter() {
  if (_transporter) return _transporter;

  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_APP_PASS;

  if (!user || !pass) {
    console.warn('[outreach] GMAIL_USER or GMAIL_APP_PASS not set.');
    return null;
  }

  _transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: { user, pass },
  });

  return _transporter;
}

// ── Anthropic client (lazy init) ─────────────────────────────
let _anthropic = null;

function getAnthropic() {
  if (_anthropic) return _anthropic;
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) {
    console.warn('[outreach] ANTHROPIC_API_KEY not set.');
    return null;
  }
  _anthropic = new Anthropic({ apiKey: key });
  return _anthropic;
}

// ── Generate email with Claude Haiku ─────────────────────────
async function generateEmail(tentativa, lead) {
  const anthropic = getAnthropic();

  // Fallback to static template if Anthropic not configured
  if (!anthropic) return getStaticTemplate(tentativa, lead);

  const shopName = lead.nome    || 'your shop';
  const cidade   = lead.cidade  || 'your area';
  const nota     = lead.nota    || 0;
  const reviews  = lead.reviews || 0;
  const temSite  = lead.tem_site ? 'yes' : 'no';

  const stepContext = [
    'This is the first time contacting them.',
    'This is a follow-up. They did not reply to the first email.',
    'This is the final follow-up. Keep it very short and low pressure.',
  ][tentativa] || '';

  const prompt = `Write a short cold email to a barbershop owner in the US.

Shop details:
- Name: ${shopName}
- City: ${cidade}
- Google rating: ${nota > 0 ? `${nota} stars` : 'not available'}
- Number of reviews: ${reviews > 0 ? reviews : 'unknown'}
- Has a website: ${temSite}

Context: ${stepContext}

Our offer: We set up a simple system for local barbershops — landing page, online booking form, and automatic SMS follow-up when a client reaches out. Setup in 48h. $149 one-time + $79/month.

Important context: Dan Cabral is a real person who will personally handle the entire process — from this first email all the way through setup and onboarding. This is not a mass blast. Dan found this shop specifically and is reaching out directly.

Rules:
- Casual, direct tone — like a real person writing, not a company
- Max 5 sentences total
- Mention ONE specific detail about their shop (rating, reviews, or missing website)
- End with a single yes/no question
- Sign as: Dan Cabral | NovuLeads
- Do NOT use buzzwords like "game-changer", "revolutionary", "leverage"
- Do NOT include a subject line — only the email body
- Plain text only, no HTML, no bullet points`;

  try {
    const response = await anthropic.messages.create({
      model:      'claude-haiku-4-5-20251001',
      max_tokens: 300,
      messages:   [{ role: 'user', content: prompt }],
    });

    const body = response.content[0]?.text?.trim();
    if (!body) throw new Error('Empty response from Haiku');

    // Generate subject separately — short and specific
    const subjectPrompts = [
      `Quick question about ${shopName}`,
      `Re: Quick question about ${shopName}`,
      `Last one from me — ${shopName}`,
    ];

    return {
      subject: subjectPrompts[tentativa],
      text:    body + '\n\n---\nDon\'t want to hear from us? Reply with STOP.',
    };

  } catch (err) {
    console.error('[outreach] Haiku generation failed, using static template:', err.message);
    return getStaticTemplate(tentativa, lead);
  }
}

// ── Static fallback templates ─────────────────────────────────
function getStaticTemplate(tentativa, lead) {
  const firstName = lead.nome?.split(' ')[0] || 'there';
  const shopName  = lead.nome   || 'your shop';
  const cidade    = lead.cidade || 'your area';

  const templates = [
    {
      subject: `Quick question about ${shopName}`,
      text:
`Hey ${firstName},

Noticed ${shopName} has great reviews on Google but no easy way for clients to book or request a cut online.

We help barbershops in ${cidade} get more bookings — landing page, booking form, and automatic follow-up texts. Takes 48h to set up.

Would this be useful for you?

— Dan Cabral | NovuLeads

---
Don't want to hear from us? Reply with STOP.`,
    },
    {
      subject: `Re: Quick question about ${shopName}`,
      text:
`Hey ${firstName}, just following up.

Most barbershops we work with were losing 3–5 bookings a week from not having an easy way for clients to reach them online.

The fix takes less than 48h. Happy to show you a quick example — no commitment.

— Dan Cabral | NovuLeads

---
Don't want to hear from us? Reply with STOP.`,
    },
    {
      subject: `Last one from me — ${shopName}`,
      text:
`Hey ${firstName},

Last follow-up — I don't want to clog your inbox.

If you ever want to add online booking and automatic follow-up texts to ${shopName}, reply and we'll set it up in 48h.

— Dan Cabral | NovuLeads

---
Don't want to hear from us? Reply with STOP.`,
    },
  ];

  return templates[tentativa] || templates[0];
}

// ── Send via Gmail ────────────────────────────────────────────
async function sendGmail({ to, subject, text }) {
  const transporter = getTransporter();
  if (!transporter) return { ok: false, error: 'gmail_not_configured' };

  const from = `Dan Cabral | NovuLeads <${process.env.GMAIL_USER}>`;

  try {
    const info = await transporter.sendMail({ from, to, subject, text });
    console.log(`[outreach] Sent to ${to} | MessageId: ${info.messageId}`);
    return { ok: true, messageId: info.messageId };
  } catch (err) {
    console.error(`[outreach] Failed to send to ${to}:`, err.message);
    return { ok: false, error: err.message };
  }
}

// ── Main worker ───────────────────────────────────────────────
async function runOutreachWorker() {
  console.log(`[outreach] Starting — ${new Date().toISOString()}`);

  const now = new Date().toISOString();

  const { data: leads, error } = await supabase
    .from('leads_prospecting')
    .select('*')
    .eq('regiao', 'US')
    .not('email', 'is', null)
    .lt('tentativas', 3)
    .or(`status.eq.novo,proximo_contato.lte.${now}`)
    .order('score', { ascending: false })
    .limit(BATCH_SIZE);

  if (error) {
    console.error('[outreach] Failed to fetch leads:', error.message);
    return;
  }

  if (!leads || leads.length === 0) {
    console.log('[outreach] No leads due. Done.');
    return;
  }

  console.log(`[outreach] Processing ${leads.length} lead(s)...`);

  for (const lead of leads) {
    await processLead(lead);
    // 2s delay between sends — avoids Gmail rate limits
    await new Promise(r => setTimeout(r, 2000));
  }

  console.log('[outreach] Done.');
}

async function processLead(lead) {
  const tentativa = lead.tentativas || 0;

  if (tentativa >= 3) {
    await supabase
      .from('leads_prospecting')
      .update({ status: 'sequencia_completa', updated_at: new Date().toISOString() })
      .eq('id', lead.id);
    return;
  }

  // Generate personalized email via Haiku
  const template = await generateEmail(tentativa, lead);

  const result = await sendGmail({
    to:      lead.email,
    subject: template.subject,
    text:    template.text,
  });

  if (!result.ok) {
    console.error(`[outreach] Failed for ${lead.email}: ${result.error}`);
    return;
  }

  // Schedule next step
  const nextTentativa  = tentativa + 1;
  const delayDays      = DELAYS_DAYS[tentativa];
  const proximoContato = delayDays
    ? new Date(Date.now() + delayDays * 24 * 60 * 60 * 1000).toISOString()
    : null;

  const novoStatus = nextTentativa >= 3 ? 'sequencia_completa' : 'em_contato';

  await supabase
    .from('leads_prospecting')
    .update({
      tentativas:      nextTentativa,
      email_enviado:   true,
      status:          novoStatus,
      ultimo_contato:  new Date().toISOString(),
      proximo_contato: proximoContato,
      updated_at:      new Date().toISOString(),
    })
    .eq('id', lead.id);

  console.log(`[outreach] Email ${nextTentativa}/3 → ${lead.email} (${lead.nome}) | next: ${proximoContato || 'none'}`);
}

// Allow running directly: node src/workers/outreach-worker.js
if (require.main === module) {
  runOutreachWorker().catch(err => {
    console.error('[outreach] Fatal error:', err);
    process.exit(1);
  });
}

module.exports = { runOutreachWorker };
